const countryCodes = {
    Brazil: "BR",
    Argentina: "AR",
    France: "FR",
    Germany: "DE",
    Spain: "ES",
    Portugal: "PT",
    Italy: "IT",
    England: "GB",
    Netherlands: "NL",
    Belgium: "BE",
    Croatia: "HR",
    Morocco: "MA",
    Japan: "JP",
    "South Korea": "KR",
    Australia: "AU",
    Mexico: "MX",
    "United States": "US",
    Canada: "CA",
    Uruguay: "UY",
    Switzerland: "CH",
    Denmark: "DK",
    Poland: "PL",
    Serbia: "RS",
    Cameroon: "CM",
    Ghana: "GH",
    Nigeria: "NG",
    Senegal: "SN",
    Tunisia: "TN",
    Qatar: "QA",
    "Saudi Arabia": "SA",
    Iran: "IR",
    Wales: "GB"
};

export default countryCodes;